"""Automated Landing Page Builder Script.

Assembles the generated marketing copy and styling into local HTML and CSS files.
"""

import os

def generate_landing_page():
    # Define the output directory
    output_dir = "dist"
    os.makedirs(output_dir, exist_ok=True)

    # HTML Content styled with the brand colors generated by your logo sub-agent (#03A9F4 and #FFC107)
    html_content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QuickFitPro - Get Fit in Minutes</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Hero Section -->
    <header class="hero">
        <div class="container">
            <span class="badge">100% Free & Private</span>
            <h1>QuickFitPro</h1>
            <p class="tagline">"Get fit in minutes, not hours. Your shortcut to a stronger, healthier you."</p>
            <p class="subtext">Designed specifically for busy professionals who need quick home workouts without sacrificing their hectic schedules.</p>
            <a href="#cta" class="btn-primary">Start Your Fitness Journey</a>
        </div>
    </header>

    <!-- Features Section -->
    <section class="features">
        <div class="container">
            <h2>Why Choose QuickFitPro?</h2>
            <div class="feature-grid">
                <div class="card">
                    <h3>⚡ Quick Workouts</h3>
                    <p>Efficient routines that can be done anywhere, anytime—even from your workspace.</p>
                </div>
                <div class="card">
                    <h3>🎯 Core Focused</h3>
                    <p>Tailored plans focusing on your core fitness goals and long-term vitality.</p>
                </div>
                <div class="card">
                    <h3>🔒 Private & Secure</h3>
                    <p>No tracking or data collection. Built with your privacy in mind.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Call to Action Section -->
    <section id="cta" class="cta-section">
        <div class="container">
            <h2>Ready to Transform Your Routine?</h2>
            <p>Join thousands of busy professionals achieving their fitness objectives daily.</p>
            <a href="#download" class="btn-secondary action-btn">Download QuickFitPro APK (Free)</a>
        </div>
    </section>

    <!-- Footer -->
    <footer>
        <p>&copy; 2026 QuickFitPro. Hosted for free via Vercel.</p>
    </footer>
</body>
</html>
"""

    # CSS Styling using your brand colors (#03A9F4 Blue and #FFC107 Accent)
    css_content = """/* Global Styles */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #333;
    line-height: 1.6;
    background-color: #f9f9f9;
}

.container {
    max-width: 1100px;
    margin: 0 auto;
    padding: 0 20px;
}

/* Hero Section */
.hero {
    background: linear-gradient(135deg, #03A9F4 0%, #0288D1 100%);
    color: #fff;
    padding: 100px 0;
    text-align: center;
}

.badge {
    background-color: #FFC107;
    color: #333;
    padding: 6px 14px;
    font-size: 0.85rem;
    font-weight: bold;
    border-radius: 20px;
    text-transform: uppercase;
    display: inline-block;
    margin-bottom: 20px;
}

.hero h1 {
    font-size: 3.5rem;
    margin-bottom: 15px;
    font-weight: 800;
}

.tagline {
    font-size: 1.4rem;
    margin-bottom: 15px;
    font-style: italic;
    opacity: 0.95;
}

.subtext {
    font-size: 1.1rem;
    max-width: 600px;
    margin: 0 auto 30px auto;
    opacity: 0.9;
}

/* Buttons */
.btn-primary {
    background-color: #FFC107;
    color: #333;
    padding: 14px 30px;
    font-size: 1.1rem;
    font-weight: bold;
    border-radius: 5px;
    text-decoration: none;
    display: inline-block;
    transition: background 0.3s ease;
}

.btn-primary:hover {
    background-color: #ffb300;
}

.btn-secondary, .action-btn {
    background-color: #03A9F4;
    color: #fff;
    padding: 14px 30px;
    font-size: 1.1rem;
    font-weight: bold;
    text-decoration: none;
    border-radius: 5px;
    display: inline-block;
    transition: background 0.3s ease;
}

.btn-secondary:hover, .action-btn:hover {
    background-color: #0288D1;
}

/* Features Section */
.features {
    padding: 80px 0;
    background-color: #fff;
    text-align: center;
}

.features h2 {
    font-size: 2.2rem;
    margin-bottom: 50px;
    color: #222;
}

.feature-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 30px;
}

.card {
    background: #fdfdfd;
    border: 1px solid #eaeaea;
    padding: 40px 30px;
    border-radius: 8px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.02);
    transition: transform 0.3s ease;
}

.card:hover {
    transform: translateY(-5px);
}

.card h3 {
    color: #03A9F4;
    margin-bottom: 15px;
    font-size: 1.3rem;
}

/* Call to Action Section */
.cta-section {
    background-color: #f1f5f9;
    padding: 70px 0;
    text-align: center;
}

.cta-section h2 {
    font-size: 2rem;
    margin-bottom: 10px;
}

.cta-section p {
    margin-bottom: 25px;
    color: #666;
}

/* Footer */
footer {
    background-color: #222;
    color: #aaa;
    text-align: center;
    padding: 25px 0;
    font-size: 0.9rem;
}
"""

    # Write files out
    html_path = os.path.join(output_dir, "index.html")
    css_path = os.path.join(output_dir, "style.css")

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(css_content)

    print("=" * 60)
    print(f"Landing page generated successfully inside folder: '{output_dir}/'")
    print(f" - {html_path}")
    print(f" - {css_path}")
    print("=" * 60)
    print("You can open 'dist/index.html' in your browser via your local server to view updates!")

if __name__ == "__main__":
    generate_landing_page()